"""Build an editorial or a combined problem set and every individual statement."""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ENTRY = re.compile(r"\\includeproblem\{([A-Z]+)\}\{([^{}]+\.tex)\}")


def find_main(source: Path) -> Path:
    source = source.resolve()
    if source.is_dir():
        source = source / "main.tex"
    elif not source.suffix:
        source = source.with_suffix(".tex")  # LaTeX Workshop's %DOC% omits .tex.
    if not source.is_file():
        raise ValueError(f"Source does not exist: {source}")
    for directory in source.parents:
        if directory.name in ("problems", "solutions"):
            main = directory / "main.tex"
            if main.is_file() and main.is_relative_to(REPO_ROOT):
                return main
    raise ValueError("Choose a .tex file under <year>/problems or <year>/solutions.")


def read_problems(directory: Path) -> list[tuple[str, str]]:
    manifest = directory / "problem-list.tex"
    entries = []
    seen = set()
    for number, line in enumerate(manifest.read_text(encoding="utf-8").splitlines(), 1):
        line = line.split("%", 1)[0].strip()
        if not line:
            continue
        match = ENTRY.fullmatch(line)
        if not match:
            raise ValueError(f"{manifest}:{number}: expected \\includeproblem{{A}}{{name.tex}}")
        letter, filename = match.groups()
        if letter in seen:
            raise ValueError(f"Duplicate problem letter: {letter}")
        source = (directory / letter / filename).resolve()
        if not source.is_relative_to((directory / letter).resolve()) or not source.is_file():
            raise ValueError(f"Missing or invalid statement: {letter}/{filename}")
        seen.add(letter)
        entries.append((letter, filename))
    if not entries:
        raise ValueError(f"No problems registered in {manifest}")
    return entries


def compile_tex(directory: Path, source: Path, output: Path | None = None) -> None:
    command = [
        "latexmk", "-xelatex", "-synctex=1", "-interaction=nonstopmode",
        "-halt-on-error", "-file-line-error",
    ]
    if output is not None:
        output.mkdir(parents=True, exist_ok=True)
        command.append(f"-outdir={output.relative_to(directory).as_posix()}")
    command.append(source.relative_to(directory).as_posix())
    print(f"\nBuilding {source.relative_to(directory)}", flush=True)
    subprocess.run(command, cwd=directory, check=True)


def build(main: Path) -> None:
    if not shutil.which("latexmk") or not shutil.which("xelatex"):
        raise ValueError("Install TeX Live or MiKTeX with latexmk and XeLaTeX, and add them to PATH.")
    directory = main.parent
    entries = read_problems(directory) if directory.name == "problems" else []
    compile_tex(directory, main)
    outputs = [main.with_suffix(".pdf")]
    for letter, filename in entries:
        output = directory / "build" / "individual"
        output.mkdir(parents=True, exist_ok=True)
        wrapper = output / f"{letter}.tex"
        content = f"% Generated by scripts/build.py.\n\\def\\SelectedProblem{{{letter}}}\n\\input{{main.tex}}\n"
        # Keep timestamps stable so latexmk can skip unchanged individual PDFs.
        if not wrapper.exists() or wrapper.read_text(encoding="utf-8") != content:
            wrapper.write_text(content, encoding="utf-8")
        compile_tex(directory, wrapper, output)
        # Publish beside the statement; keep wrappers and intermediates in build/.
        compiled_pdf = output / f"{letter}.pdf"
        published_pdf = (directory / letter / filename).with_suffix(".pdf")
        if not published_pdf.exists() or published_pdf.read_bytes() != compiled_pdf.read_bytes():
            shutil.copyfile(compiled_pdf, published_pdf)
        outputs.append(published_pdf)
    print("\nPDFs ready:", flush=True)
    for output in outputs:
        print(f"  {output.relative_to(REPO_ROOT)}", flush=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Main or child .tex file, or problems/solutions directory")
    args = parser.parse_args()
    try:
        build(find_main(args.source))
    except (ValueError, OSError) as error:
        print(f"Build error: {error}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as error:
        print(f"LaTeX build failed (exit {error.returncode}). See the log above.", file=sys.stderr)
        return error.returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
